// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;

namespace Nutrition.Data
{
    public partial class NutritionContext : DbContext
    {
        public NutritionContext()
        {
        }

        public NutritionContext(DbContextOptions<NutritionContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Nutrient> Nutrient { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Nutrient>(entity =>
            {
                entity.HasIndex(e => e.NutrientGuid)
                    .HasName("IX_NutrientGUID")
                    .IsUnique();

                entity.Property(e => e.NutrientId).HasColumnName("NutrientID");

                entity.Property(e => e.NutrientDescription).IsRequired();

                entity.Property(e => e.NutrientGuid)
                    .IsRequired()
                    .HasColumnName("NutrientGUID")
                    .HasMaxLength(500);

                entity.Property(e => e.NutrientName)
                    .IsRequired()
                    .HasMaxLength(50);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}