// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Nutrition.Data
{
    public partial class Nutrient
    {
        public int NutrientId { get; }
        public string NutrientName { get; set; }
        public string NutrientDescription { get; set; }
        public Guid NutrientGuid { get; private set; } = new Guid();
    }
}