SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF  NOT EXISTS (SELECT * FROM sys.objects 
WHERE object_id = OBJECT_ID(N'[dbo].[Nutrient]') AND type in (N'U'))

BEGIN
	CREATE TABLE [dbo].[Nutrient](
		[NutrientID] [int] IDENTITY(1,1) NOT NULL ,
		[NutrientName] [nvarchar](50) NOT NULL,
		[NutrientDescription] [nvarchar](max) NOT NULL,
		[NutrientGUID] UNIQUEIDENTIFIER NOT NULL ,
	CONSTRAINT [PK_NutrientID] PRIMARY KEY CLUSTERED
	(
		[NutrientID] ASC
	),
	CONSTRAINT [IX_NutrientGUID] UNIQUE NONCLUSTERED
	(
		[NutrientGUID] ASC
	)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,
	IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON,
	ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END